//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengDDAC1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Items = new HashSet<Item>();
            this.Vessels = new HashSet<Vessel>();
        }
    
        public int customerID { get; set; }

        [Display(Name = "Customer Name:")]
        [Required]
        public string customerName { get; set; }

        [Display(Name = "IC:")]
        [Required]
        public string customerIC { get; set; }

        [Display(Name = "Date of Birth:")]
        [Required]
        public Nullable<System.DateTime> customerDateOfBirth { get; set; }

        [Display(Name = "Address:")]
        [Required]
        public string customerAddress { get; set; }

        [Display(Name = "Phone No:")]
        [Required]
        public string customerPhoneNo { get; set; }
        public Nullable<int> customerVessel { get; set; }
    
        public virtual Vessel Vessel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vessel> Vessels { get; set; }
    }
}
