//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengDDAC1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int itemID { get; set; }
        public string itemName { get; set; }
        [Required]
        public Nullable<int> itemQuantity { get; set; }
        [Required]
        public int itemCustomer { get; set; }
        [Required]
        public Nullable<int> itemVessel { get; set; }
        [Required]

        public virtual Customer Customer { get; set; }
        public virtual Vessel Vessel { get; set; }
    }
}
